import type {
  RecentSettlement,
  SettlementArtist,
  SettlementProduct,
} from '../types/settlement-calculation-types';

export const MOCK_SETTLEMENT_ARTISTS: SettlementArtist[] = [
  {
    contractId: 1,
    imageUrl: '',
    name: '김롱이',
    category: '액세서리',
    settlementDate: '매월 10일',
    daysRemaining: 'D-3',
    status: 'PENDING',
    statusLabel: '정산대상',
  },
  {
    contractId: 2,
    imageUrl: '',
    name: '별사탕나라',
    category: '인테리어 소품',
    settlementDate: '매월 10일',
    daysRemaining: 'D-3',
    status: 'PAID',
    statusLabel: '지급완료',
  },
  {
    contractId: 3,
    imageUrl: '',
    name: '재미나이',
    category: '문구',
    settlementDate: '매월 10일',
    daysRemaining: 'D+27',
    status: 'UNPAID',
    statusLabel: '미지급',
  },
  {
    contractId: 4,
    imageUrl: '',
    name: '김작가',
    category: '일러스트-아트',
    settlementDate: '매월 10일',
    daysRemaining: 'D+27',
    status: 'UNPAID',
    statusLabel: '미지급',
  },
  {
    contractId: 5,
    imageUrl: '',
    name: '박아리',
    category: '일러스트-아트',
    settlementDate: '매월 10일',
    daysRemaining: 'D+27',
    status: 'UNPAID',
    statusLabel: '미지급',
  },
];

export const MOCK_RECENT_SETTLEMENTS: RecentSettlement[] = [
  {
    id: 1,
    rank: 1,
    artistName: '김별이',
    settlementAmount: 10000,
    settlementDate: '2025.09.19',
    paymentMethod: 'PG',
    paymentMethodLabel: 'PG',
  },
  {
    id: 2,
    rank: 2,
    artistName: '하하하',
    settlementAmount: 10000,
    settlementDate: '2025.09.19',
    paymentMethod: 'MANUAL',
    paymentMethodLabel: '수동',
  },
  {
    id: 3,
    rank: 3,
    artistName: '하오오',
    settlementAmount: 10000,
    settlementDate: '2025.09.19',
    paymentMethod: 'PG',
    paymentMethodLabel: 'PG',
  },
  {
    id: 4,
    rank: 4,
    artistName: '제주남다수',
    settlementAmount: 10000,
    settlementDate: '2025.09.19',
    paymentMethod: 'PG',
    paymentMethodLabel: 'PG',
  },
  {
    id: 5,
    rank: 5,
    artistName: '가영스타',
    settlementAmount: 10000,
    settlementDate: '2025.09.19',
    paymentMethod: 'MANUAL',
    paymentMethodLabel: '수동',
  },
];

export const MOCK_SETTLEMENT_PRODUCTS: Record<number, SettlementProduct[]> = {
  1: [
    {
      contractProductId: 101,
      imageUrl: '',
      productName: '1번 소품 어쩌구 저쩌구 소푸우우우움',
      price: 10000,
      salesQuantity: 1,
      commission: '30%',
      marginAmount: 3000,
      settlementAmount: 7000,
      artistName: '박아리',
      lastInboundDate: '2025.09.10',
    },
    {
      contractProductId: 102,
      imageUrl: '',
      productName: '2번 소품 어쩌구 저쩌구 소푸우우우움',
      price: 10000,
      salesQuantity: 1,
      commission: '25%',
      marginAmount: 2500,
      settlementAmount: 7500,
      artistName: '박아리',
      lastInboundDate: '2025.09.10',
    },
    {
      contractProductId: 103,
      imageUrl: '',
      productName: '3번 소품 어쩌구 저쩌구 소푸우우우움',
      price: 10000,
      salesQuantity: 0,
      commission: '35%',
      marginAmount: 3500,
      settlementAmount: 6500,
      artistName: '박아리',
      lastInboundDate: '2025.08.10',
    },
  ],
  2: [
    {
      contractProductId: 201,
      imageUrl: '',
      productName: '인테리어 소품 A',
      price: 25000,
      salesQuantity: 3,
      commission: '20%',
      marginAmount: 5000,
      settlementAmount: 20000,
      artistName: '별사탕나라',
      lastInboundDate: '2025.09.05',
    },
  ],
};
