import type {
  RecentSettlementItem,
  ShopSettlement,
  TaxInvoiceItem,
} from '../types/settlement-management-types';

export const MOCK_SHOP_SETTLEMENTS: ShopSettlement[] = [
  {
    contractId: 1,
    imageUrl: '',
    shopName: '1번소품샵',
    category: '액세서리',
    settlementDate: '매월 6일',
    daysRemaining: 'D-4',
    status: 'COMPLETED',
    statusLabel: '정산완료',
  },
  {
    contractId: 2,
    imageUrl: '',
    shopName: '2번소품샵',
    category: '인테리어 소품',
    settlementDate: '매월 10일',
    daysRemaining: 'D-0',
    status: 'COMPLETED',
    statusLabel: '정산완료',
  },
  {
    contractId: 3,
    imageUrl: '',
    shopName: '3번소품샵',
    category: '문구',
    settlementDate: '매월 11일',
    daysRemaining: 'D+1',
    status: 'DELAYED',
    statusLabel: '정산지연',
  },
  {
    contractId: 4,
    imageUrl: '',
    shopName: '4번소품샵',
    category: '일러스트-아트',
    settlementDate: '매월 8일',
    daysRemaining: 'D-2',
    status: 'PENDING',
    statusLabel: '정산대상',
  },
  {
    contractId: 5,
    imageUrl: '',
    shopName: '5번소품샵',
    category: '일러스트-아트',
    settlementDate: '매월 10일',
    daysRemaining: 'D-0',
    status: 'COMPLETED',
    statusLabel: '정산완료',
  },
  {
    contractId: 6,
    imageUrl: '',
    shopName: '6번소품샵',
    category: '일러스트-아트',
    settlementDate: '매월 10일',
    daysRemaining: 'D-0',
    status: 'COMPLETED',
    statusLabel: '정산완료',
  },
  {
    contractId: 7,
    imageUrl: '',
    shopName: '7번소품샵',
    category: '인테리어 소품',
    settlementDate: '매월 10일',
    daysRemaining: 'D-0',
    status: 'COMPLETED',
    statusLabel: '정산완료',
  },
  {
    contractId: 8,
    imageUrl: '',
    shopName: '8번소품샵',
    category: '문구',
    settlementDate: '매월 11일',
    daysRemaining: 'D+1',
    status: 'DELAYED',
    statusLabel: '정산지연',
  },
  {
    contractId: 9,
    imageUrl: '',
    shopName: '9번소품샵',
    category: '일러스트-아트',
    settlementDate: '매월 8일',
    daysRemaining: 'D-2',
    status: 'PENDING',
    statusLabel: '정산대상',
  },
  {
    contractId: 10,
    imageUrl: '',
    shopName: '10번소품샵',
    category: '일러스트-아트',
    settlementDate: '매월 10일',
    daysRemaining: 'D-0',
    status: 'COMPLETED',
    statusLabel: '정산완료',
  },
  {
    contractId: 11,
    imageUrl: '',
    shopName: '11번소품샵',
    category: '일러스트-아트',
    settlementDate: '매월 10일',
    daysRemaining: 'D-0',
    status: 'COMPLETED',
    statusLabel: '정산완료',
  },
];

export const MOCK_RECENT_SETTLEMENTS: RecentSettlementItem[] = [
  {
    id: 1,
    rank: 1,
    shopName: '2번소품샵',
    settlementAmount: 10000,
    settlementDate: '2025.09.10',
    paymentMethod: 'PG',
    paymentMethodLabel: 'PG',
  },
  {
    id: 2,
    rank: 2,
    shopName: '5번소품샵',
    settlementAmount: 10000,
    settlementDate: '2025.09.10',
    paymentMethod: 'MANUAL',
    paymentMethodLabel: '수동',
  },
  {
    id: 3,
    rank: 3,
    shopName: '6번소품샵',
    settlementAmount: 10000,
    settlementDate: '2025.09.10',
    paymentMethod: 'PG',
    paymentMethodLabel: 'PG',
  },
  {
    id: 4,
    rank: 4,
    shopName: '7번소품샵',
    settlementAmount: 10000,
    settlementDate: '2025.09.10',
    paymentMethod: 'PG',
    paymentMethodLabel: 'PG',
  },
  {
    id: 5,
    rank: 5,
    shopName: '8번소품샵',
    settlementAmount: 10000,
    settlementDate: '2025.09.10',
    paymentMethod: 'MANUAL',
    paymentMethodLabel: '수동',
  },
  {
    id: 6,
    rank: 6,
    shopName: '11번소품샵',
    settlementAmount: 10000,
    settlementDate: '2025.09.10',
    paymentMethod: 'PG',
    paymentMethodLabel: 'PG',
  },
  {
    id: 7,
    rank: 7,
    shopName: '10번소품샵',
    settlementAmount: 10000,
    settlementDate: '2025.09.10',
    paymentMethod: 'MANUAL',
    paymentMethodLabel: '수동',
  },
  {
    id: 8,
    rank: 8,
    shopName: '15번소품샵',
    settlementAmount: 10000,
    settlementDate: '2025.09.10',
    paymentMethod: 'PG',
    paymentMethodLabel: 'PG',
  },
  {
    id: 9,
    rank: 9,
    shopName: '14번소품샵',
    settlementAmount: 10000,
    settlementDate: '2025.09.10',
    paymentMethod: 'PG',
    paymentMethodLabel: 'PG',
  },
  {
    id: 10,
    rank: 10,
    shopName: '16번소품샵',
    settlementAmount: 10000,
    settlementDate: '2025.09.10',
    paymentMethod: 'MANUAL',
    paymentMethodLabel: '수동',
  },
  {
    id: 11,
    rank: 11,
    shopName: '17번소품샵',
    settlementAmount: 10000,
    settlementDate: '2025.09.10',
    paymentMethod: 'PG',
    paymentMethodLabel: 'PG',
  },
  {
    id: 12,
    rank: 12,
    shopName: '20번소품샵',
    settlementAmount: 10000,
    settlementDate: '2025.09.10',
    paymentMethod: 'PG',
    paymentMethodLabel: 'PG',
  },
];

export const MOCK_TAX_INVOICE_ITEMS: TaxInvoiceItem[] = [
  {
    id: 1,
    shopName: '1번소품샵',
    settlementAmount: 10000,
    settlementDate: '2025.09.10',
    status: 'COMPLETED',
    statusLabel: '정산완료',
  },
  {
    id: 2,
    shopName: '2번소품샵',
    settlementAmount: 10000,
    settlementDate: '2025.09.10',
    status: 'COMPLETED',
    statusLabel: '정산완료',
  },
  {
    id: 3,
    shopName: '3번소품샵',
    settlementAmount: 10000,
    settlementDate: '2025.09.10',
    status: 'COMPLETED',
    statusLabel: '정산완료',
  },
  {
    id: 4,
    shopName: '4번소품샵',
    settlementAmount: 10000,
    settlementDate: '2025.09.10',
    status: 'COMPLETED',
    statusLabel: '정산완료',
  },
  {
    id: 5,
    shopName: '5번소품샵',
    settlementAmount: 10000,
    settlementDate: '2025.09.10',
    status: 'COMPLETED',
    statusLabel: '정산완료',
  },
  {
    id: 6,
    shopName: '6번소품샵',
    settlementAmount: 10000,
    settlementDate: '2025.09.10',
    status: 'COMPLETED',
    statusLabel: '정산완료',
  },
  {
    id: 7,
    shopName: '7번소품샵',
    settlementAmount: 10000,
    settlementDate: '2025.09.10',
    status: 'COMPLETED',
    statusLabel: '정산완료',
  },
  {
    id: 8,
    shopName: '8번소품샵',
    settlementAmount: 10000,
    settlementDate: '2025.09.10',
    status: 'COMPLETED',
    statusLabel: '정산완료',
  },
];
